type=page
status=published
title=Setup and Configuration
next=using.html
prev=install.html
~~~~~~
include::attributes.conf[]
Setup and Configuration
=======================

[[GBFVV]]


[[running-the-tck]]
4 Running the TCK
-----------------

This chapter describes how to use the {TechnologyShortName} TCK.
This chapter contains the following sections:

* link:#GHGDG[Generating the SMAPs to be Tested]
* link:#GBFUY[Using the {TechnologyShortName} TCK to Test a Product]

{TechnologyShortName} TCK Operating Assumptions
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
The following is assumed: +
* J2SE SDK version 1.4 or later is installed on the system hosting the test.
* The Product to be tested (which implements {TechnologyShortName} {TechnologyVersion})
  is installed on the system hosting the test.

include::config.inc[]

[[GBFUY]][[using-the-tck-to-test-product]]

4.2 Using the {TechnologyShortName} TCK to Test a Product
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The following test is applied, one SMAP at a time, to each SMAP generated by the
procedures above. The test is executed by launching the Java programming language
class VerifySMAP (in dsol-tck.jar) with the SMAP as an argument: +

`java VerifySMAP -classpath TCK_DIRECTORY/dsol-tck.jar path_to_the_smap`

For example, to test an unresolved SMAP file pass it to the test: +
  `java VerifySMAP my.smap`
For example, to test a class file with an embedded SMAP pass it to the test: +
  `java VerifySMAP my.class`

If a test fails an exception will be thrown. If the test of any SMAP fails,
the TCK has failed.
