type=page
status=published
title=Introduction
next=rules.html
prev=preface.html
~~~~~~
include::attributes.conf[]
Introduction
============

[[GBFOW]]


[[introduction]]
1 Introduction
--------------

This chapter provides an overview of the principles that apply
generally to all Technology Compatibility Kits (TCKs) and describes the
{TechnologyFullName} TCK ({TechnologyShortName} {TechnologyVersion} TCK).
It also includes a high level listing
of what is needed to get up and running with the {TechnologyShortName}
TCK.

This chapter includes the following topics:

* link:#GBFTK[Compatibility Testing]
* link:#GBFQR[About the TCK]
* link:#GBFQW[Getting Started With the TCK]

[[GBFTK]][[compatibility-testing]]

1.1 Compatibility Testing
~~~~~~~~~~~~~~~~~~~~~~~~~

Compatibility testing differs from traditional product testing in a
number of ways. The focus of compatibility testing is to test those
features and areas of an implementation that are likely to differ across
other implementations, such as those features that:

* Rely on hardware or operating system-specific behavior
* Are difficult to port
* Mask or abstract hardware or operating system behavior

Compatibility test development for a given feature relies on a complete
specification and compatible implementation (CI) for that feature.
Compatibility testing is not primarily concerned with robustness,
performance, nor ease of use.

[[GBFQN]][[why-compatibility-testing-is-important]]

1.1.1 Why Compatibility Testing is Important
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Jakarta platform compatibility is important to different groups involved
with Jakarta technologies for different reasons:

* Compatibility testing ensures that the Jakarta platform does not become
fragmented as it is ported to different operating systems and hardware
environments.
* Compatibility testing benefits developers working in the Jakarta
programming language, allowing them to write applications once and then
to deploy them across heterogeneous computing environments without
porting.
* Compatibility testing allows application users to obtain applications
from disparate sources and deploy them with confidence.
* Conformance testing benefits Jakarta platform implementors by ensuring a
level playing field for all Jakarta platform ports.

[[GBFPR]][[tck-compatibility-rules]]

1.1.2 TCK Compatibility Rules
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Compatibility criteria for all technology implementations are embodied
in the TCK Compatibility Rules that apply to a specified technology.
Each TCK tests for adherence to these Rules as described in
link:rules.html#GBFSN[Chapter 2, "Procedure for Certification."]

[[GBFPW]][[tck-overview]]

1.1.3 TCK Overview
^^^^^^^^^^^^^^^^^^

A TCK is a set of tools and tests used to verify that a vendor's compatible
implementation of a Jakarta EE technology conforms to the applicable
specification. All tests in the TCK are based on the written
specifications for the Jakarta EE platform. A TCK tests compatibility of a
vendor's compatible implementation of the technology to the applicable
specification of the technology. Compatibility testing is a means of
ensuring correctness, completeness, and consistency across all
implementations developed by technology licensees.

The set of tests included with each TCK is called the test suite. Most
tests in a TCK's test suite are self-checking, but some tests may
require tester interaction. Most tests return either a Pass or Fail
status. For a given platform to be certified, all of the required tests
must pass. The definition of required tests may change from platform to
platform.

The definition of required tests will change over time. Before your
final certification test pass, be sure to download the latest version
of this TCK.

[[GBFPB]][[java-community-process-jcp-program-and-compatibility-testing]]

1.1.4 Jakarta EE Specification Process (JESP) Program and Compatibility Testing
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

The Jakarta EE Specification Process (JESP) program is the formalization of the
open process that has been used since 2019 to develop and revise Jakarta EE
technology specifications in cooperation with the international Jakarta EE
community. The JESP program specifies that the following three major
components must be included as deliverables in a final Jakarta EE technology
release under the direction of the responsible Expert Group:

* Technology Specification
* Compatible Implementation (CI)
* Technology Compatibility Kit (TCK)

For further information about the JESP program, go to Jakarta EE Specification
Process community page https://jakarta.ee/specifications.

[[GBFQR]][[about-the-tck]]

1.2 About the TCK
~~~~~~~~~~~~~~~~~

The {TechnologyShortName} TCK {TechnologyVersion} is designed as a
portable, configurable, automated test suite for verifying the
compatibility of a vendor's implementation of the
{TechnologyShortName} {TechnologyVersion} Specification.

The {TechnologyShortName} does not define APIs, but instead defines a
data format and process. As a result, the TCK is different than most, it verifies the
data format, and thus indirectly the process. The input to the process is source code
in an arbitrary language, and thus the process cannot be directly tested by the TCK.

[[GBFQV]][[tck-specifications-and-requirements]]

1.2.1 TCK Specifications and Requirements
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

This section lists the applicable requirements and specifications.

* Specification Requirements: Software requirements for a
{TechnologyShortName} implementation are described in detail in the
{TechnologyShortName} {TechnologyVersion} Specification.  Links to the
{TechnologyShortName} specification and other product information can
be found at {SpecificationURL}.
* {TechnologyShortName} Version: The {TechnologyShortName} {TechnologyVersion} TCK
is based on the {TechnologyShortName}
Specification, Version {TechnologyVersion}.
* Compatible Implementation: One {TechnologyShortName}
{TechnologyVersion} Compatible Implementation, {TechnologyRI} is
available from the Eclipse EE4J project
(https://projects.eclipse.org/projects/ee4j). See the CI documentation page at
{TechnologyRIURL} for more information.

See the {TechnologyShortName} TCK Release Notes for more specific
information about Java SE version requirements, supported platforms,
restrictions, and so on.
